main:
  params: [input]
  steps:
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - service_url: ${input.url} # The Cloud Run URL for our MCP Server
    - call_mcp_server:
        try:
          call: http.get
          args:
            url: ${service_url + "/latest-updates"}
            auth:
              type: OIDC
          result: mcp_response
        retry:
          predicate: ${http.default_retry_predicate}
          max_retries: 5
          backoff:
            initial_delay: 1
            max_delay: 60
            multiplier: 2
    - return_result:
        return: ${mcp_response.body}
