import { useState } from 'react'
import { Info, UserPlus, CheckCircle, Search, MessageCircle } from 'lucide-react'

function App() {
  const [query, setQuery] = useState('')
  const [chatHistory, setChatHistory] = useState([
    { role: 'assistant', content: 'Hello! I am your Election Process Education Assistant. How can I help you understand the voting process in India today?' }
  ])
  const [isLoading, setIsLoading] = useState(false)

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    if (!query.trim()) return

    // Add user query to chat
    setChatHistory(prev => [...prev, { role: 'user', content: query }])
    setIsLoading(true)
    setQuery('')

    // Simulate API call to Vertex AI Agent / MCP Server
    setTimeout(() => {
      setChatHistory(prev => [...prev, { 
        role: 'assistant', 
        content: 'I am currently running in a simulated mode. In the production version, this response would be generated by the Vertex AI Agent Builder, grounded in the official election knowledge base.' 
      }])
      setIsLoading(false)
    }, 1500)
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans">
      {/* Header */}
      <header className="bg-primary text-white p-6 shadow-md">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <CheckCircle className="w-8 h-8 text-white" />
            <h1 className="text-2xl font-bold tracking-tight">ElectionAssist India</h1>
          </div>
          <nav className="hidden md:flex gap-6 text-sm font-medium">
            <a href="#about" className="hover:text-slate-200 transition-colors">About</a>
            <a href="#features" className="hover:text-slate-200 transition-colors">Topics</a>
            <a href="#assistant" className="bg-white text-primary px-4 py-2 rounded-full hover:bg-slate-100 transition-colors">Ask Assistant</a>
          </nav>
        </div>
      </header>

      <main className="max-w-5xl mx-auto p-6 grid gap-12 mt-8">
        {/* Hero Section */}
        <section className="text-center space-y-6 py-12">
          <h2 className="text-4xl md:text-5xl font-extrabold text-slate-800">
            Understand the <span className="text-primary">Electoral Process</span>
          </h2>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto leading-relaxed">
            A neutral, accessible, and comprehensive guide to participating in Indian elections. Get verified information on eligibility, registration, and polling day procedures.
          </p>
        </section>

        {/* Feature Cards */}
        <section id="features" className="grid md:grid-cols-3 gap-6">
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
            <div className="bg-blue-50 w-12 h-12 rounded-lg flex items-center justify-center mb-4 text-primary">
              <UserPlus className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-semibold mb-2">Voter Registration</h3>
            <p className="text-slate-600 text-sm">Learn how to enroll online via the Voter Portal or offline. Know the required documents.</p>
          </div>
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
            <div className="bg-teal-50 w-12 h-12 rounded-lg flex items-center justify-center mb-4 text-secondary">
              <Info className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-semibold mb-2">Polling Station</h3>
            <p className="text-slate-600 text-sm">Step-by-step guide on what happens at the booth, identifying officers, and casting your vote.</p>
          </div>
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
            <div className="bg-rose-50 w-12 h-12 rounded-lg flex items-center justify-center mb-4 text-accent">
              <CheckCircle className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-semibold mb-2">EVM & VVPAT</h3>
            <p className="text-slate-600 text-sm">Understand the technology behind the Electronic Voting Machines and how to verify your vote.</p>
          </div>
        </section>

        {/* Assistant Section */}
        <section id="assistant" className="bg-white rounded-3xl shadow-lg border border-slate-200 overflow-hidden flex flex-col h-[600px]">
          <div className="bg-slate-50 border-b border-slate-200 p-4 flex items-center gap-3">
            <div className="bg-primary p-2 rounded-full text-white">
              <MessageCircle className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-semibold text-slate-800">Election Education Assistant</h3>
              <p className="text-xs text-slate-500">Powered by Vertex AI & RAG</p>
            </div>
          </div>
          
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {chatHistory.map((msg, idx) => (
              <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[80%] p-4 rounded-2xl text-sm ${
                  msg.role === 'user' 
                    ? 'bg-primary text-white rounded-tr-sm' 
                    : 'bg-slate-100 text-slate-800 rounded-tl-sm border border-slate-200'
                }`}>
                  {msg.content}
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex justify-start">
                <div className="bg-slate-100 text-slate-500 p-4 rounded-2xl rounded-tl-sm border border-slate-200 flex gap-2 items-center">
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce"></div>
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce delay-75"></div>
                  <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce delay-150"></div>
                </div>
              </div>
            )}
          </div>

          <div className="p-4 border-t border-slate-200 bg-white">
            <form onSubmit={handleSearch} className="relative">
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Ask about eligibility, EVMs, registration..."
                className="w-full pl-4 pr-12 py-4 bg-slate-50 border border-slate-200 rounded-full focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all text-sm"
              />
              <button 
                type="submit" 
                disabled={!query.trim() || isLoading}
                className="absolute right-2 top-2 bottom-2 bg-primary text-white p-2 rounded-full hover:bg-primary/90 transition-colors disabled:opacity-50"
              >
                <Search className="w-5 h-5" />
              </button>
            </form>
          </div>
        </section>
      </main>
      
      <footer className="bg-slate-900 text-slate-400 py-8 text-center text-sm mt-12">
        <p>© 2026 ElectionAssist. For educational purposes only.</p>
        <p className="mt-2 text-slate-500">Not an official government website.</p>
      </footer>
    </div>
  )
}

export default App
